// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs-AWfhnDV-m0UjtYJXU7NYsJ_d6A7_WQ',
    appId: '1:1086818738482:web:5b6466e9c10dd04b85b72b',
    messagingSenderId: '1086818738482',
    projectId: 'nfl-franchise-information',
    authDomain: 'nfl-franchise-information.firebaseapp.com',
    storageBucket: 'nfl-franchise-information.appspot.com',
    measurementId: 'G-8X4PNEM4Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVCzQjv5YhDY3uBbCTwaXZnaP4rR3YyE',
    appId: '1:1086818738482:android:0be6c8dc2d9b546f85b72b',
    messagingSenderId: '1086818738482',
    projectId: 'nfl-franchise-information',
    storageBucket: 'nfl-franchise-information.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbBrXZDuPCbE88xQ7hMLBgJj0HBa4e35E',
    appId: '1:1086818738482:ios:2e1f2a8b26e6bcb185b72b',
    messagingSenderId: '1086818738482',
    projectId: 'nfl-franchise-information',
    storageBucket: 'nfl-franchise-information.appspot.com',
    iosClientId: '1086818738482-mgucpujeo7ceihe80vs26iq20gr9q2jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nflFranchiseInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbBrXZDuPCbE88xQ7hMLBgJj0HBa4e35E',
    appId: '1:1086818738482:ios:3bfe06ef976d211a85b72b',
    messagingSenderId: '1086818738482',
    projectId: 'nfl-franchise-information',
    storageBucket: 'nfl-franchise-information.appspot.com',
    iosClientId: '1086818738482-nhqf19eukp1s41orfk4ltadfk39d2fsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.nflFranchiseInformation.RunnerTests',
  );
}
